DROP TABLE CALENDARIO.Notificacao;
DROP TABLE CALENDARIO.FormaNotificacao
DROP TAbLE Calendario.evento;
DROP TABLE Calendario.tipo;
DROP TABLE CALENDARIO.Usuario;

DROP TABLE CALENDARIO.Session;

DROP PROCEDURE CALENDARIO.trEventoCheck;

DROP SCHEMA CALENDARIO;